name: Build, Provenance & Reproducibility

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write  # needed for provenance OIDC token (future full SLSA attestation)
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: read
  pull-requests: read
  security-events: none
  statuses: read

concurrency:
  group: provenance-repro-${{ github.ref }}
  cancel-in-progress: false

env:
  SOURCE_DATE_EPOCH: 1700000000
  NODE_VERSION: '18.19.0'

jobs:
  build:
    name: Build & Hash
    runs-on: ubuntu-latest
    outputs:
      base64_subjects: ${{ steps.subjects.outputs.encoded }}
      overall_sha256: ${{ steps.hash.outputs.overall_sha256 }}
    steps:
      - name: Checkout
        # Pinned actions/checkout@v4 (update SHA periodically)
        uses: actions/checkout@b4ffde65f46336ab0da05f224ef0f1088f6e61b1 # v4.1.6
      - name: Setup Node
        # Pinned actions/setup-node@v4 (update SHA periodically)
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install (clean)
        run: npm ci
      - name: Build
        run: npm run build
      - name: Hash manifest (dist/)
        id: hash
        run: |
          set -e
          if [ -d dist ]; then
            find dist -type f -print0 | sort -z | xargs -0 sha256sum > dist.sha256sum || true
          fi
          if [ -s dist.sha256sum ]; then
            overall=$(sha256sum dist.sha256sum | cut -d' ' -f1)
            echo "overall_sha256=$overall" >> $GITHUB_OUTPUT
            echo "Computed overall dist digest: $overall"
          else
            echo 'No dist files found; skipping digest.'
          fi
      - name: Create provenance reference JSON
        if: steps.hash.outputs.overall_sha256
        run: |
          cat > provenance-reference.json <<EOF
          {
            "binaryDistDigest": "sha256:${{ steps.hash.outputs.overall_sha256 }}",
            "sourceDateEpoch": "${SOURCE_DATE_EPOCH}",
            "schema": 1
          }
          EOF
          mkdir -p evidence
          cp provenance-reference.json evidence/provenance.json
      - name: Encode SLSA subjects (base64)
        id: subjects
        if: steps.hash.outputs.overall_sha256
        run: |
          set -e
          line="betanet-linter:sha256:${{ steps.hash.outputs.overall_sha256 }}"
          echo "Subject line: $line"
          # Cross-platform base64 (GNU vs BSD)
          if base64 --help 2>&1 | grep -qi -- '-w'; then
            encoded=$(printf '%s' "$line" | base64 -w0)
          else
            encoded=$(printf '%s' "$line" | base64)
          fi
          echo "encoded=$encoded" >> "$GITHUB_OUTPUT"
          echo "Base64 subjects: $encoded"
      - name: Upload build artifacts
        # Pinned actions/upload-artifact@v4
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.3
        with:
          name: build-dist-${{ github.run_number }}
          path: |
            dist/
            dist.sha256sum
            evidence/provenance.json
          retention-days: 7

  provenance:
    name: Generate SLSA Provenance
    needs: build
    if: needs.build.outputs.base64_subjects != ''
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: ${{ needs.build.outputs.base64_subjects }}
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  rebuild:
    name: Rebuild & Verify
    needs: [build, provenance]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab0da05f224ef0f1088f6e61b1 # v4.1.6
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install (clean)
        run: npm ci
      - name: Build
        run: npm run build
      - name: Compute new manifest
        run: |
          if [ -d dist ]; then
            find dist -type f -print0 | sort -z | xargs -0 sha256sum > dist.sha256sum || true
            sha256sum dist.sha256sum | cut -d' ' -f1 > overall.sha || true
          fi
      - name: Download original artifacts
        # Pinned actions/download-artifact@v4
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: build-dist-${{ github.run_number }}
          path: original
      - name: Diff manifests
        run: |
          if [ -f original/dist.sha256sum ] && [ -f dist.sha256sum ]; then
            echo 'Comparing manifests...'
            if diff -u original/dist.sha256sum dist.sha256sum; then
              echo '✅ Rebuild manifests match.'
            else
              echo '❌ Rebuild manifests differ.'
              exit 1
            fi
          else
            echo 'Skipping diff (missing manifest).'
          fi
      - name: Run linter with provenance evidence
        run: |
          npm install -g .
          if [ -f original/evidence/provenance.json ]; then
            betanet-lint check bin/cli.js --output json --evidence-file original/evidence/provenance.json > compliance-with-provenance.json || true
            jq '.checks[] | select(.id==9) | {id,evidenceType,details}' compliance-with-provenance.json || true
          else
            echo 'No provenance evidence available.'
          fi
      - name: Upload verification outputs
        # Pinned actions/upload-artifact@v4 (same pin as build job)
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.3
        with:
          name: reproducibility-verification-${{ github.run_number }}
          path: |
            dist.sha256sum
            overall.sha
            compliance-with-provenance.json
          retention-days: 7
